// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfbspimsxjhkvvyxmxji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmYnNwaW1zeGpoa3Z2eXhteGppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MDA4NzUsImV4cCI6MjA2ODM3Njg3NX0.RcJ08AUVB44rFIZ33nc1WZ_af2X6qucW16ogQJBImVQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});