// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dcuhuvruznwimupiiqpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjdWh1dnJ1em53aW11cGlpcXBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NjY0NjIsImV4cCI6MjA3MzU0MjQ2Mn0.UQ9oChYIosiaJr-rYpHMBNtLfPm1_NYcJLSTyMe_y5E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});